# Generated by Django 5.2.9 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='抢购名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('purchase_limit_per_customer', models.IntegerField(default=1, verbose_name='每客户限购数量')),
                ('total_quantity_limit', models.IntegerField(blank=True, null=True, verbose_name='总数量限制')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='flash_sale_banners/', verbose_name='横幅图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '限时抢购',
                'verbose_name_plural': '限时抢购',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='优惠码')),
                ('coupon_type', models.CharField(choices=[('percentage', '百分比折扣'), ('fixed_amount', '固定金额'), ('free_shipping', '免运费'), ('bogo', '买一送一')], max_length=20, verbose_name='优惠券类型')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='折扣值')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='折扣百分比')),
                ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最低购买金额')),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最大折扣金额')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='使用次数限制')),
                ('usage_per_customer', models.IntegerField(default=1, verbose_name='每客户使用次数')),
                ('usage_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='已使用次数')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('for_new_customers_only', models.BooleanField(default=False, verbose_name='仅限新客户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='coupons', to='products.productcategory')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='products.product')),
                ('customer_limit', models.ManyToManyField(blank=True, related_name='personal_coupons', to='accounts.customer')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折扣金额')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order')),
            ],
            options={
                'verbose_name': '优惠券使用记录',
                'verbose_name_plural': '优惠券使用记录',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='抢购价格')),
                ('quantity_limit', models.IntegerField(blank=True, null=True, verbose_name='数量限制')),
                ('sold_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='已售数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_products', to='promotions.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='products.product')),
            ],
            options={
                'verbose_name': '限时抢购商品',
                'verbose_name_plural': '限时抢购商品',
            },
        ),
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(through='promotions.FlashSaleProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='促销名称')),
                ('promotion_type', models.CharField(choices=[('percentage_discount', '百分比折扣'), ('fixed_amount_discount', '固定金额折扣'), ('buy_x_get_y', '买X送Y'), ('bundle', '捆绑销售'), ('free_shipping', '免运费'), ('gift_with_purchase', '赠品')], max_length=50, verbose_name='促销类型')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='折扣值')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='折扣百分比')),
                ('scope', models.CharField(choices=[('entire_order', '整单'), ('specific_products', '指定商品'), ('product_category', '商品分类'), ('collection', '商品集合')], default='entire_order', max_length=50, verbose_name='适用范围')),
                ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最低购买金额')),
                ('minimum_quantity', models.IntegerField(blank=True, null=True, verbose_name='最低购买数量')),
                ('maximum_usage_per_customer', models.IntegerField(blank=True, null=True, verbose_name='每客户最大使用次数')),
                ('gift_quantity', models.IntegerField(default=1, verbose_name='赠品数量')),
                ('buy_quantity', models.IntegerField(blank=True, null=True, verbose_name='购买数量')),
                ('get_quantity', models.IntegerField(blank=True, null=True, verbose_name='获得数量')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='使用次数限制')),
                ('usage_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='已使用次数')),
                ('priority', models.IntegerField(default=0, help_text='数值越大优先级越高', verbose_name='优先级')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotion_banners/', verbose_name='横幅图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('get_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_get_promotions', to='products.product')),
                ('gift_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_promotions', to='products.product')),
                ('target_categories', models.ManyToManyField(blank=True, related_name='promotions', to='products.productcategory')),
                ('target_products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product')),
            ],
            options={
                'verbose_name': '促销活动',
                'verbose_name_plural': '促销活动',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active'], name='promotions__code_fd37bc_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_until'], name='promotions__valid_f_d8a470_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleproduct',
            unique_together={('flash_sale', 'product')},
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='promotions__is_acti_6fdf95_idx'),
        ),
    ]
