# Generated by Django 5.2.9 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('alipay', '支付宝'), ('wechat_pay', '微信支付'), ('bank_transfer', '银行转账'), ('cash_on_delivery', '货到付款')], max_length=50, unique=True, verbose_name='支付网关')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API密钥')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API密钥')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook密钥')),
                ('environment', models.CharField(choices=[('sandbox', '沙箱'), ('production', '生产')], default='sandbox', max_length=20, verbose_name='环境')),
                ('config', models.JSONField(default=dict, verbose_name='配置信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付网关配置',
                'verbose_name_plural': '支付网关配置',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='支付方式名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='支付方式代码')),
                ('payment_type', models.CharField(choices=[('card', '银行卡'), ('digital_wallet', '电子钱包'), ('bank_transfer', '银行转账'), ('cod', '货到付款')], max_length=50, verbose_name='支付类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('supports_refund', models.BooleanField(default=True, verbose_name='支持退款')),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='手续费比例')),
                ('processing_fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='固定手续费')),
                ('gateway_name', models.CharField(blank=True, max_length=100, verbose_name='支付网关')),
                ('gateway_config', models.JSONField(default=dict, verbose_name='网关配置')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标类名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付方式',
                'verbose_name_plural': '支付方式',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='支付单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='支付金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币代码')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('authorized', '已授权'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('refunded', '已退款'), ('partially_refunded', '部分退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='手续费')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='网关交易ID')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='网关响应')),
                ('gateway_error', models.TextField(blank=True, verbose_name='网关错误')),
                ('payer_name', models.CharField(blank=True, max_length=100, verbose_name='付款人姓名')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='付款人邮箱')),
                ('payer_phone', models.CharField(blank=True, max_length=20, verbose_name='付款人电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(max_length=50, unique=True, verbose_name='退款单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='退款金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币代码')),
                ('reason', models.TextField(verbose_name='退款原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='退款状态')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='网关交易ID')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='网关响应')),
                ('gateway_error', models.TextField(blank=True, verbose_name='网关错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to='accounts.staff')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payments_pa_payment_a0847d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
    ]
