# Generated by Django 5.2.9 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='原因名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='原因代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('requires_explanation', models.BooleanField(default=False, verbose_name='需要说明')),
                ('requires_photos', models.BooleanField(default=False, verbose_name='需要照片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '退货原因',
                'verbose_name_plural': '退货原因',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='政策名称')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认政策')),
                ('return_period_days', models.IntegerField(default=30, verbose_name='退货期限(天)')),
                ('allow_partial_returns', models.BooleanField(default=True, verbose_name='允许部分退货')),
                ('require_original_packaging', models.BooleanField(default=False, verbose_name='需要原包装')),
                ('require_tags_attached', models.BooleanField(default=False, verbose_name='需要标签完好')),
                ('allow_used_items', models.BooleanField(default=False, verbose_name='允许使用后退货')),
                ('customer_pays_return_shipping', models.BooleanField(default=False, verbose_name='客户承担退货运费')),
                ('restocking_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='重新上架费比例')),
                ('refund_methods', models.JSONField(default=list, verbose_name='退款方式')),
                ('exchange_timeframe_days', models.IntegerField(default=14, verbose_name='换货期限(天)')),
                ('notes', models.TextField(blank=True, verbose_name='政策说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('excluded_categories', models.ManyToManyField(blank=True, related_name='excluded_from_returns', to='products.productcategory')),
                ('excluded_products', models.ManyToManyField(blank=True, related_name='excluded_from_returns', to='products.product')),
            ],
            options={
                'verbose_name': '退货政策',
                'verbose_name_plural': '退货政策',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='退货单号')),
                ('return_type', models.CharField(choices=[('refund', '退款'), ('exchange', '换货'), ('store_credit', '商店信用')], max_length=20, verbose_name='退货类型')),
                ('status', models.CharField(choices=[('requested', '已申请'), ('reviewing', '审核中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('waiting_for_return', '等待退货'), ('received', '已收到退货'), ('inspecting', '检查中'), ('refunded', '已退款'), ('exchanged', '已换货'), ('completed', '已完成'), ('cancelled', '已取消')], default='requested', max_length=30, verbose_name='退货状态')),
                ('explanation', models.TextField(blank=True, verbose_name='详细说明')),
                ('requested_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='申请退款金额')),
                ('approved_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='批准退款金额')),
                ('actual_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='实际退款金额')),
                ('return_shipping_method', models.CharField(blank=True, max_length=100, verbose_name='退货物流方式')),
                ('return_tracking_number', models.CharField(blank=True, max_length=100, verbose_name='退货追踪号码')),
                ('return_carrier', models.CharField(blank=True, max_length=100, verbose_name='退货承运商')),
                ('photos', models.JSONField(default=list, verbose_name='照片证据')),
                ('notes', models.TextField(blank=True, verbose_name='处理备注')),
                ('internal_notes', models.TextField(blank=True, verbose_name='内部备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='收到退货时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to='accounts.staff')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='returns.returnreason')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_returns', to='accounts.staff')),
            ],
            options={
                'verbose_name': '退货申请',
                'verbose_name_plural': '退货申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='退货数量')),
                ('condition', models.CharField(choices=[('new', '全新未使用'), ('like_new', '几乎全新'), ('used', '已使用'), ('damaged', '损坏'), ('defective', '有缺陷'), ('wrong_item', '错误商品'), ('missing_parts', '缺少零件')], default='used', max_length=20, verbose_name='商品状况')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('received', '已收到'), ('inspected', '已检查'), ('approved', '已批准'), ('rejected', '已拒绝'), ('refunded', '已退款'), ('exchanged', '已换货')], default='pending', max_length=20, verbose_name='状态')),
                ('requested_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='申请退款金额')),
                ('actual_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='实际退款金额')),
                ('inspection_notes', models.TextField(blank=True, verbose_name='检查备注')),
                ('restocked', models.BooleanField(default=False, verbose_name='已重新入库')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exchange_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanged_for', to='products.product')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='returns.returnrequest')),
            ],
            options={
                'verbose_name': '退货商品',
                'verbose_name_plural': '退货商品',
                'ordering': ['return_request', 'order_item'],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['return_number'], name='returns_ret_return__7635ad_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='returns_ret_order_i_7316d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returnitem',
            unique_together={('return_request', 'order_item')},
        ),
    ]
