# Generated by Django 5.2.9 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('level', models.CharField(choices=[('bronze', '青铜会员'), ('silver', '白银会员'), ('gold', '黄金会员'), ('platinum', '白金会员'), ('diamond', '钻石会员')], max_length=20, unique=True, verbose_name='等级代码')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='折扣率')),
                ('min_points', models.IntegerField(default=0, verbose_name='最小积分')),
                ('max_points', models.IntegerField(blank=True, null=True, verbose_name='最大积分')),
                ('benefits', models.JSONField(default=list, verbose_name='会员权益')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户等级',
                'verbose_name_plural': '客户等级',
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮件')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话号码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='邮箱验证时间')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='用户名')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='姓')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='忠诚度积分')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总消费金额')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='加入日期')),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='最后购买日期')),
                ('shipping_address', models.JSONField(default=list, verbose_name='配送地址')),
                ('billing_address', models.JSONField(default=dict, verbose_name='账单地址')),
                ('preferences', models.JSONField(default=dict, verbose_name='偏好设置')),
                ('total_orders', models.IntegerField(default=0, verbose_name='总订单数')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='已完成订单')),
                ('cancelled_orders', models.IntegerField(default=0, verbose_name='已取消订单')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.customerlevel')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['-total_spent'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(verbose_name='积分数量')),
                ('transaction_type', models.CharField(choices=[('earn', '获得'), ('deduct', '扣除'), ('expire', '过期'), ('adjust', '调整')], max_length=20, verbose_name='交易类型')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='原因')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='参考ID')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='accounts.customer')),
            ],
            options={
                'verbose_name': '积分交易记录',
                'verbose_name_plural': '积分交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='员工编号')),
                ('department', models.CharField(choices=[('warehouse', '仓库'), ('sales', '销售'), ('customer_service', '客服'), ('management', '管理'), ('it', 'IT'), ('finance', '财务'), ('marketing', '市场')], max_length=50, verbose_name='部门')),
                ('role', models.CharField(choices=[('staff', '员工'), ('supervisor', '主管'), ('manager', '经理'), ('director', '总监'), ('admin', '管理员')], default='staff', max_length=50, verbose_name='角色')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职状态')),
                ('permissions', models.JSONField(default=dict, verbose_name='权限配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['department', 'role'],
            },
        ),
    ]
