# Generated by Django 5.2.9 on 2025-12-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetask',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_tasks', to='orders.order'),
        ),
        migrations.AddField(
            model_name='warehousetask',
            name='related_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_tasks', to='shipping.shipment'),
        ),
        migrations.AddField(
            model_name='reservationallocation',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_adjustments', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='adjustmentitem',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_items', to='inventory.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='orders.order'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product'),
        ),
        migrations.AddField(
            model_name='reservationallocation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.stockreservation'),
        ),
        migrations.AddField(
            model_name='warehousetask',
            name='related_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_tasks', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='warehousetask',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_from', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='warehousetask',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items_dest', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_items', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items_source', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='inventory.warehousetask'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='warehousetask',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseaisle',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseequipment',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='warehouseequipment',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using_equipments', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='warehouseequipment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseperformancemetrics',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousesafetycheck',
            name='conducted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_safety_checks', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='warehousesafetycheck',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_safety_checks', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='warehousesafetycheck',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseshelf',
            name='aisle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='inventory.warehouseaisle'),
        ),
        migrations.AddField(
            model_name='warehousestaffschedule',
            name='assigned_tasks',
            field=models.ManyToManyField(blank=True, related_name='assigned_schedules', to='inventory.warehousetask'),
        ),
        migrations.AddField(
            model_name='warehousestaffschedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_schedules', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='warehousestaffschedule',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.stockadjustment'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_transactions', to='products.product'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transactions', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_to', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousezone',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousestaffschedule',
            name='primary_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff', to='inventory.warehousezone'),
        ),
        migrations.AddField(
            model_name='warehouseaisle',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='inventory.warehousezone'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['product', 'status'], name='inventory_s_product_c68e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order', 'status'], name='inventory_s_order_i_9b314c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at'], name='inventory_s_expires_9d6a1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationallocation',
            unique_together={('reservation', 'inventory')},
        ),
        migrations.AddIndex(
            model_name='warehousetask',
            index=models.Index(fields=['task_number'], name='inventory_w_task_nu_a78b90_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetask',
            index=models.Index(fields=['warehouse', 'status', 'priority'], name='inventory_w_warehou_f84206_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetask',
            index=models.Index(fields=['assigned_to', 'status'], name='inventory_w_assigne_0de78b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_i_product_f6b65e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['status', 'expiry_date'], name='inventory_i_status_2e747f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'warehouse', 'batch_number')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouseperformancemetrics',
            unique_together={('warehouse', 'metric_date', 'period_type')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouseshelf',
            unique_together={('aisle', 'shelf_number')},
        ),
        migrations.AddIndex(
            model_name='warehousetransaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='inventory_w_transac_30d3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransaction',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_w_product_0e1dfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousestaffschedule',
            unique_together={('staff', 'work_date')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouseaisle',
            unique_together={('warehouse', 'aisle_number')},
        ),
    ]
