# Generated by Django 5.2.9 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='承运商名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='承运商代码')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('website', models.URLField(blank=True, verbose_name='网站')),
                ('api_integrated', models.BooleanField(default=False, verbose_name='API集成')),
                ('api_config', models.JSONField(default=dict, verbose_name='API配置')),
                ('services', models.JSONField(default=list, verbose_name='服务列表')),
                ('tracking_url_template', models.CharField(blank=True, max_length=500, verbose_name='追踪网址模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '承运商',
                'verbose_name_plural': '承运商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='配送方式名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='配送方式代码')),
                ('method_type', models.CharField(choices=[('standard', '标准配送'), ('express', '快递'), ('overnight', '隔夜达'), ('same_day', '当日达'), ('pickup', '自提'), ('international', '国际配送')], default='standard', max_length=50, verbose_name='配送类型')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基础费用')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='每公斤费用')),
                ('cost_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='每件费用')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='免运费阈值')),
                ('estimated_days_min', models.IntegerField(default=3, verbose_name='最短预计天数')),
                ('estimated_days_max', models.IntegerField(default=7, verbose_name='最长预计天数')),
                ('cutoff_time', models.TimeField(blank=True, null=True, verbose_name='当日截止时间')),
                ('available_countries', models.JSONField(default=list, verbose_name='可用国家')),
                ('available_regions', models.JSONField(default=list, verbose_name='可用地区')),
                ('available_postal_codes', models.JSONField(default=list, verbose_name='可用邮编范围')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大重量(kg)')),
                ('max_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大长度(cm)')),
                ('max_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大宽度(cm)')),
                ('max_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大高度(cm)')),
                ('max_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大体积(m³)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配送方式',
                'verbose_name_plural': '配送方式',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(max_length=50, unique=True, verbose_name='发货单号')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('packing', '包装中'), ('ready', '准备发货'), ('shipped', '已发货'), ('in_transit', '运输中'), ('out_for_delivery', '配送中'), ('delivered', '已送达'), ('failed', '投递失败'), ('returned', '已退回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='发货状态')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='追踪号码')),
                ('tracking_url', models.URLField(blank=True, verbose_name='追踪网址')),
                ('shipping_address', models.JSONField(default=dict, verbose_name='配送地址')),
                ('package_count', models.IntegerField(default=1, verbose_name='包裹数量')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总重量(kg)')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总体积(m³)')),
                ('carrier_name', models.CharField(blank=True, max_length=100, verbose_name='承运商')),
                ('carrier_service', models.CharField(blank=True, max_length=100, verbose_name='承运服务')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='预计送达时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='实际送达时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_shipments', to='accounts.staff')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_shipments', to='accounts.staff')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingmethod')),
            ],
            options={
                'verbose_name': '发货单',
                'verbose_name_plural': '发货单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('package_number', models.CharField(blank=True, max_length=50, verbose_name='包裹编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='orders.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='shipping.shipment')),
            ],
            options={
                'verbose_name': '发货项目',
                'verbose_name_plural': '发货项目',
                'unique_together': {('shipment', 'order_item')},
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['shipment_number'], name='shipping_sh_shipmen_33cb73_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'status'], name='shipping_sh_order_i_242975_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipping_sh_trackin_af3d4f_idx'),
        ),
    ]
