# Generated by Django 5.2.9 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待付款'), ('payment_review', '支付审核'), ('processing', '处理中'), ('on_hold', '暂停'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunded', '已退款'), ('failed', '失败')], default='draft', max_length=20, verbose_name='订单状态')),
                ('payment_status', models.CharField(choices=[('pending', '待支付'), ('authorized', '已授权'), ('paid', '已支付'), ('partially_paid', '部分支付'), ('refunded', '已退款'), ('voided', '已作废')], default='pending', max_length=20, verbose_name='支付状态')),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', '未发货'), ('partially_fulfilled', '部分发货'), ('fulfilled', '已发货'), ('delivered', '已送达'), ('returned', '已退回')], default='unfulfilled', max_length=20, verbose_name='发货状态')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税费')),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金额')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='订单总额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付金额')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退款金额')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='支付方式')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, verbose_name='支付网关')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='支付交易ID')),
                ('shipping_method', models.CharField(blank=True, max_length=100, verbose_name='配送方式')),
                ('shipping_address', models.JSONField(default=dict, verbose_name='配送地址')),
                ('billing_address', models.JSONField(default=dict, verbose_name='账单地址')),
                ('customer_note', models.TextField(blank=True, verbose_name='客户备注')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='客户邮箱')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='客户电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='优惠券代码')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='accounts.staff')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总价')),
                ('quantity_shipped', models.IntegerField(default=0, verbose_name='已发货数量')),
                ('quantity_refunded', models.IntegerField(default=0, verbose_name='已退款数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('allocated_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': '订单项目',
                'verbose_name_plural': '订单项目',
                'ordering': ['order', 'product'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_count', models.IntegerField(default=0, verbose_name='商品数量')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税费')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总计')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金额')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='优惠券代码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='accounts.customer')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总价')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.shoppingcart')),
            ],
            options={
                'verbose_name': '购物车项目',
                'verbose_name_plural': '购物车项目',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status'], name='orders_orde_created_49d91d_idx'),
        ),
    ]
