# Generated by Django 5.2.9 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='属性名称')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='属性代码')),
                ('type', models.CharField(choices=[('text', '文本'), ('integer', '整数'), ('boolean', '布尔')], max_length=20, verbose_name='类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='必填')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='可筛选')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '产品属性',
                'verbose_name_plural': '产品属性',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='分类图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta标题')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='简短描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销售价格')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成本价格')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='比较价格')),
                ('is_track_inventory', models.BooleanField(default=True, verbose_name='跟踪库存')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('reorder_level', models.IntegerField(default=10, verbose_name='补货点')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='低库存阈值')),
                ('allow_backorder', models.BooleanField(default=False, verbose_name='允许缺货订购')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量(kg)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='尺寸(LxWxH cm)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='颜色')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='尺寸')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='材质')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_featured', models.BooleanField(default=False, verbose_name='推荐产品')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='热销产品')),
                ('is_new', models.BooleanField(default=False, verbose_name='新品')),
                ('is_digital', models.BooleanField(default=False, verbose_name='数字产品')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta标题')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta描述')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta关键词')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='平均评分')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='评价数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='图片')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='替代文本')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否主图')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('comment', models.TextField(blank=True, verbose_name='内容')),
                ('is_approved', models.BooleanField(default=False, verbose_name='已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': '产品评价',
                'verbose_name_plural': '产品评价',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='变动数量')),
                ('action', models.CharField(choices=[('increase', '增加'), ('decrease', '减少'), ('adjust', '调整'), ('reserve', '预留'), ('release', '释放')], max_length=20, verbose_name='操作类型')),
                ('current_stock', models.PositiveIntegerField(verbose_name='变动后库存')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='关联单号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_changes', to='products.product')),
            ],
            options={
                'verbose_name': '库存变动',
                'verbose_name_plural': '库存变动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='值')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': '产品属性值',
                'verbose_name_plural': '产品属性值',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['slug', 'is_active'], name='products_pr_slug_e8e9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
    ]
